# fly.toml app configuration file generated for radar-postgres on 2024-01-13T19:01:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "radar-postgres"
primary_region = "atl"

[env]
  FLY_SCALE_TO_ZERO = "1h"
  PRIMARY_REGION = "atl"

[[mounts]]
  source = "pg_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 5432
  auto_start_machines = true

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  protocol = "tcp"
  internal_port = 5432 # Postgres instance (https://fly.io/docs/postgres/connecting/connecting-external/)
  auto_start_machines = true

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/vm"

[[metrics]]
  port = 9187
  path = "/metrics"
